autoDetectedPackages:
- com.loghelper.annotation
- com.loghelper.aop
- com.loghelper.configuration
- com.loghelper.handler
- com.loghelper.util
- com.loghelper.loghelper
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
startOnDebug: false
